### ISSUE TITLE
0.12.1나오면 전용 apl로 만들어주세요^^

### ISSUE THREAD

**Issue by shingoon1030** [HelloWorld017/MineCombat#3]
부탁드립니다 많은섭에서 이용하고있으니

**Comment by HelloWorld017** [comment]
현재 CombatPlus라고 전용 API로 만들어 놓긴 했는데, 풀러그인 방식이 아니라 테스트에 어려움이 있어 원본님한테 방법을 바꿔달라고 요청은 했습니다.

**Comment by HelloWorld017** [comment]
아마 guns폴더에 phar를 넣는 방식이 아닌 따로 plugins에 phar를 넣는 방식으로 바뀌면 다시 개발하겠습니다.
